export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';
export const SEARCH_COUNTRY_BY_NAME = 'SEARCH_COUNTRY_BY_NAME';
export const SORT_COUNTRIES = 'SORT_COUNTRIES';
export const LOAD_COUNTRIES = 'LOAD_COUNTRIES';
export const COUNTRIES_FETCHED = 'COUNTRIES_FETCHED';
export const COUNTRIES_FETCH_ERROR = 'COUNTRIES_FETCH_ERROR';
export const COUNTRY_FETCHED = 'COUNTRY_FETCHED';
export const COUNTRY_FETCH_ERROR = 'COUNTRY_FETCH_ERROR';
